//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProizvPR.DBConn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public int id_comment { get; set; }
        public int id_request { get; set; }
        public int id_user { get; set; }
        public string comment_text { get; set; }
        public Nullable<System.DateTime> comment_date { get; set; }
    
        public virtual Requests Requests { get; set; }
        public virtual Users Users { get; set; }
    }
}
