//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProizvPR.DBConn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Failure_types
    {
        public Failure_types()
        {
            this.Requests = new HashSet<Requests>();
        }
    
        public int id_failure_type { get; set; }
        public string type_name { get; set; }
    
        public virtual ICollection<Requests> Requests { get; set; }
    }
}
