//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProizvPR.DBConn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logins
    {
        public Logins()
        {
            this.Users = new HashSet<Users>();
        }
    
        public int id_login { get; set; }
        public string login { get; set; }
        public string password { get; set; }
    
        public virtual ICollection<Users> Users { get; set; }
    }
}
