//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProizvPR.DBConn
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PROIZVPREntities : DbContext
    {
        public PROIZVPREntities()
            : base("name=PROIZVPREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Clients> Clients { get; set; }
        public DbSet<Comments> Comments { get; set; }
        public DbSet<Equipment> Equipment { get; set; }
        public DbSet<Failure_types> Failure_types { get; set; }
        public DbSet<Logins> Logins { get; set; }
        public DbSet<Repair_actions> Repair_actions { get; set; }
        public DbSet<Requests> Requests { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<Statuses> Statuses { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
