//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProizvPR.DBConn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public Requests()
        {
            this.Comments = new HashSet<Comments>();
            this.Repair_actions = new HashSet<Repair_actions>();
        }
    
        public int id_request { get; set; }
        public string request_number { get; set; }
        public System.DateTime creation_date { get; set; }
        public string description { get; set; }
        public int id_equipment { get; set; }
        public int id_failure_type { get; set; }
        public int id_client { get; set; }
        public int id_status { get; set; }
        public Nullable<int> assigned_to { get; set; }
        public Nullable<System.DateTime> deadline_date { get; set; }
        public string extension_reason { get; set; }
        public Nullable<bool> client_agreement { get; set; }
        public Nullable<bool> qr_code_generated { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual ICollection<Comments> Comments { get; set; }
        public virtual Equipment Equipment { get; set; }
        public virtual Failure_types Failure_types { get; set; }
        public virtual ICollection<Repair_actions> Repair_actions { get; set; }
        public virtual Users Users { get; set; }
        public virtual Statuses Statuses { get; set; }
    }
}
