//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProizvPR.DBConn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Comments = new HashSet<Comments>();
            this.Repair_actions = new HashSet<Repair_actions>();
            this.Repair_actions1 = new HashSet<Repair_actions>();
            this.Requests = new HashSet<Requests>();
        }
    
        public int id_user { get; set; }
        public string full_name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public int id_role { get; set; }
        public int id_login { get; set; }
    
        public virtual ICollection<Comments> Comments { get; set; }
        public virtual Logins Logins { get; set; }
        public virtual ICollection<Repair_actions> Repair_actions { get; set; }
        public virtual ICollection<Repair_actions> Repair_actions1 { get; set; }
        public virtual ICollection<Requests> Requests { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
